ci:
  autoupdate_schedule: quarterly

default_stages: [commit]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/janosh/format-ipy-cells
    rev: v0.1.7
    hooks:
      - id: format-ipy-cells

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: '.svg$'
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        # MD013: Line length
        # MD029: Ordered list item prefix
        # MD033: Inline HTML
        # MD034: Bare URL used
        args: [-r, '~MD013,~MD029,~MD033,~MD034']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        stages: [commit-msg]
